### PR TITLE
Update regexes.json

### PR DESCRIPTION
**Pull request by thezakman**
Removed the  duplicated regex "(A3T[A-Z0-9]|AKIA|AGPA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}"

### CODE REVIEW

**Comment by umair-rhl** [comment]
Thanks for the Pull request Pedro, I missed removing these entries, I already notice a few more duplicates, will try to remove those as well tonight, but feel free to help out with improving the tool in future as well, I will be looking forward and thanks again :)

**Comment by thezakman** [comment]
Absolutely, I'm more than happy to help.
Have a good one brother!

**Comment by umair-rhl** [comment]
Hey Pedro, we are working on a v2 release in the next couple of days and have made some major improvements in terms of regexes including an increase of the secret types count from 33 to 83 something types and an addition of severity tags within the output.
The execution format is the same as before. Repo: https://github.com/redhuntlabs/BucketLoot/tree/v2-dev

Would love to hear your thoughts :)

Cheers!

**Comment by thezakman** [comment]
Hi Umair,

This is fantastic news! I plan to put it to the test this week and provide my feedback. Just from my initial glance at the changes and updates, it seems like the tool is definitely moving in the right direction. 

Congratulations on your hard work! I'll be sure to get in touch once I've thoroughly tested it.

Cheers!

**Comment by thezakman** [comment]
Hi @umair-rhl, I've tested the tool, and it's looking fantastic! 

Great job with the work you've done. 
I plan to contribute by sharing some regex that I've developed for a few of my security tools. Once I find some free time, I'll make a commit. 

Cheers!

**Pull request merged**
